/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/common/ActionButton.vue')['default']
    AppAlert: typeof import('./src/components/common/AppAlert.vue')['default']
    AppConfirmDialog: typeof import('./src/components/common/modal/AppConfirmDialog.vue')['default']
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    BotList: typeof import('./src/components/bot-list/BotList.vue')['default']
    ModalBotInfo: typeof import('./src/components/common/modal/ModalBotInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipEllipsis: typeof import('./src/components/common/TooltipEllipsis.vue')['default']
  }
}
