/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppSuccessDialog: typeof import('./src/components/common/modal/AppSuccessDialog.vue')['default']
    BotList: typeof import('./src/components/bot-list/BotList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModalBotInfo: typeof import('./src/components/common/modal/ModalBotInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
