/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmSaveDialog: typeof import('./src/components/common/dialog/ConfirmSaveDialog.vue')['default']
    FormVisval: typeof import('./src/components/FormVisval.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ResultDialog: typeof import('./src/components/common/dialog/ResultDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinnerOverlay: typeof import('./src/components/common/spinner/SpinnerOverlay.vue')['default']
  }
}
